[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 8MB
board_upload.flash_size = 8MB

lib_deps =
    moononournation/GFX Library for Arduino@^1.4.7

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
